apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    app: gateway
    type: microservice
spec:
  containers:
    - name: gateway-app
      image: tomidziurdzia/servicios.api.gateway:latest
      ports:
        - containerPort: 80