apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-libreria-app
      image: tomidziurdzia/servicios.api.seguridad:latest
      ports:
        - containerPort: 80
      env:
        - name: ConnectionStrings__ConexionDB
          value: Server=mssql-service;Database=Seguridad;User=sa:Password=Walter@960