apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:6.0.18
      command:
        - /bin/bash
        - -c
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "tomidziurdzia"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "Walter@960"
      ports:
        - containerPort: 27017