apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  labels:
    app: microservice-seguridad
    name: mssql-pod
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/server
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Walter@960"
      ports:
        - containerPort: 1433